import { Helmet } from 'react-helmet-async';
import { ShieldAlert, AlertTriangle, Info, Shield, BrainCircuit } from 'lucide-react';

const Disclaimer = () => {
  return (
    <div className="min-h-screen pt-24 pb-12 bg-slate-50 dark:bg-slate-900">
      <Helmet><title>Disclaimer - StudentAI Tools</title></Helmet>
      
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-12">
          <div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-amber-50 dark:bg-amber-900/30 text-amber-500 mb-4 shadow-sm">
            <ShieldAlert className="w-8 h-8" />
          </div>
          <h1 className="text-4xl md:text-5xl font-extrabold text-slate-900 dark:text-white mb-6">Disclaimer</h1>
          <p className="text-lg text-slate-600 dark:text-slate-400">Please read this disclaimer carefully before using our AI tools. Last updated: {new Date().toLocaleDateString()}</p>
        </div>

        <div className="glass-card rounded-[2.5rem] shadow-sm border border-slate-200 dark:border-slate-800 p-8 md:p-14 prose prose-slate dark:prose-invert max-w-none prose-h2:text-2xl prose-h2:font-bold prose-h2:mt-10 prose-h2:mb-4">
          <p className="lead font-medium">
            The information contained on StudentAI Tools website (the "Service") is for general information and educational purposes only.
          </p>

          <h2 className="flex items-center gap-3"><Info className="w-6 h-6 text-amber-500" /> 1. No Professional Advice</h2>
          <p>
            The information and tools provided by StudentAI Tools do not constitute professional academic, legal, or financial advice. While we strive to provide the most advanced educational utilities, we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, or suitability of the generated text, math calculations, or citations.
          </p>

          <h2 className="flex items-center gap-3"><Shield className="w-6 h-6 text-amber-500" /> 2. Academic Integrity & Usage</h2>
          <p>
            Our core AI tools (including Essay Writers, Homework Helpers, and Summary Generators) are exclusively designed as <strong>study aids</strong> to provide structural inspiration, research outlines, and writing support. They are explicitly <strong>not</strong> intended to bypass educational assignments or plagiarize content.
          </p>
          <p>
            Users are solely responsible for ensuring that their use of StudentAI Tools complies with their specific school, university, or institution's absolute academic integrity policies. We expressly disclaim any liability for academic discipline resulting from the misuse of these tools.
          </p>

          <h2 className="flex items-center gap-3"><AlertTriangle className="w-6 h-6 text-amber-500" /> 3. External Links & Advertisements (AdSense)</h2>
          <p>
            Through this website, you are able to link to other websites which are not under the direct control of StudentAI Tools. We have zero control over the nature, content, and availability of those third-party sites.
          </p>
          <p>
            The inclusion of any links, <strong>specifically advertisements natively served by the Google AdSense network</strong>, does not necessarily imply a direct recommendation or rigidly endorse the views expressed within those advertisements.
          </p>

          <h2 className="flex items-center gap-3"><BrainCircuit className="w-6 h-6 text-amber-500" /> 4. AI Hallucinations & Errors</h2>
          <p>
            Artificial Intelligence language models (LLMs) dynamically predict text and can occasionally produce incorrect, biased, nonsensical, or "hallucinated" results. 
          </p>
          <p className="font-bold border-l-4 border-amber-500 pl-4 py-2 bg-amber-50 dark:bg-amber-900/20 text-slate-800 dark:text-slate-200 rounded-r-lg mt-4">
            You must always independently verify critical facts, mathematical calculations, and specific claims generated by our tools before officially submitting them in any academic or professional capacity.
          </p>

          <h2>5. Affiliates and Earnings Disclosure</h2>
          <p>
            StudentAI Tools is primarily a free service supported almost entirely by programmatic advertising revenue (such as Google AdSense). We may periodically participate in specific affiliate marketing programs, which strictly means we may get paid minor commissions on editorially chosen external products purchased seamlessly through our outbound links.
          </p>

          <h2>Contact Us</h2>
          <p>
            If you seriously have any questions or require significantly more information about our site's specific disclaimers, please actively feel free to contact us via our official Contact Page.
          </p>
        </div>
      </div>
    </div>
  );
};

export default Disclaimer;
