import { Helmet } from 'react-helmet-async';
import { Scale, CheckCircle, FileText } from 'lucide-react';

const Terms = () => {
  return (
    <div className="min-h-screen pt-24 pb-12 bg-slate-50 dark:bg-slate-900">
      <Helmet><title>Terms & Conditions - StudentAI Tools</title></Helmet>
      
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-12">
          <div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-indigo-50 dark:bg-indigo-900/30 text-indigo-500 mb-4 shadow-sm">
            <Scale className="w-8 h-8" />
          </div>
          <h1 className="text-4xl md:text-5xl font-extrabold text-slate-900 dark:text-white mb-6">Terms & Conditions</h1>
          <p className="text-lg text-slate-600 dark:text-slate-400">Please read these terms carefully before using our services.</p>
        </div>

        <div className="glass-card rounded-[2.5rem] shadow-sm border border-slate-200 dark:border-slate-800 p-8 md:p-14 prose prose-slate dark:prose-invert max-w-none prose-h2:text-2xl prose-h2:font-bold prose-h2:mt-10 prose-h2:mb-4">
          <p className="lead font-medium">
            Welcome to StudentAI Tools. By accessing this website, we assume you accept these terms and conditions. Do not continue to use StudentAI Tools if you do not agree to take all of the terms and conditions stated on this page.
          </p>

          <h2 className="flex items-center gap-3"><FileText className="w-6 h-6 text-indigo-500" /> 1. License and Usage</h2>
          <p>Unless otherwise stated, StudentAI Tools and/or its licensors own the intellectual property rights for all material on StudentAI Tools. All intellectual property rights are reserved. You may access this from StudentAI Tools for your own personal use subjected to restrictions set in these terms and conditions.</p>
          <p>You must not:</p>
          <ul>
            <li>Republish material from StudentAI Tools</li>
            <li>Sell, rent or sub-license material from StudentAI Tools</li>
            <li>Reproduce, duplicate or copy material from StudentAI Tools</li>
            <li>Automate requests, scrape, or excessively ping our API backend</li>
          </ul>

          <h2 className="flex items-center gap-3"><CheckCircle className="w-6 h-6 text-indigo-500" /> 2. User Generated Content & AI Output</h2>
          <p>The content generated by our AI tools (including but not limited to resumes, presentations, essays, and captions) is provided "as is". Machine learning models can sometimes produce inaccurate, biased, or highly repetitive output.</p>
          <p><strong>Disclaimer of Reliability:</strong> We are not responsible for the inaccuracies of generated content. You, the user, are solely responsible for reviewing, editing, and verifying any content before using it in a professional, academic, or legal setting.</p>

          <h2>3. Academic Integrity Clause</h2>
          <p>You explicitly agree not to use StudentAI Tools to bypass institutional rules regarding academic honesty. The intent of our platform is to provide study aids, outlining assistance, and structural formatting help. Engaging in direct, unedited plagiarism submitting AI-generated essays as entirely your own work violates our intended usage guidelines.</p>

          <h2>4. Cookies & Advertising</h2>
          <p>We employ the use of cookies. By accessing StudentAI Tools, you agreed to use cookies in agreement with the StudentAI Tools's Privacy Policy. Most interactive websites use cookies to let us retrieve the user's details for each visit. We also utilize third-party ad networks (like Google AdSense) which utilize cookies as outlined in our Privacy Statement.</p>

          <h2>5. Disclaimer of Warranties</h2>
          <p>To the maximum extent permitted by applicable law, we exclude all representations, warranties and conditions relating to our website and the use of this website. Nothing in this disclaimer will:</p>
          <ul>
            <li>limit or exclude our or your liability for death or personal injury;</li>
            <li>limit or exclude our or your liability for fraud or fraudulent misrepresentation;</li>
            <li>limit any of our or your liabilities in any way that is not permitted under applicable law; or</li>
          </ul>

          <h2>6. Updates to these Terms</h2>
          <p>We reserve the right to revise these terms and conditions at any time. By using this website, you are expected to review these terms on a regular basis.</p>

        </div>
      </div>
    </div>
  );
};

export default Terms;
