import { Helmet } from 'react-helmet-async';

const Terms = () => (
  <div className="min-h-screen pt-24 pb-12 bg-slate-50 dark:bg-slate-900">
    <Helmet><title>Terms & Conditions - StudentAI Tools</title></Helmet>
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 bg-white dark:bg-slate-800 p-10 rounded-3xl shadow-sm border border-slate-200 dark:border-slate-700">
      <h1 className="text-4xl font-bold text-slate-900 dark:text-white mb-8">Terms and Conditions</h1>
      <div className="prose dark:prose-invert max-w-none text-slate-600 dark:text-slate-300 space-y-6">
        <h2 className="text-2xl font-semibold text-slate-800 dark:text-white mt-8 mb-4">1. Acceptable Usage</h2>
        <p>You agree not to misuse our services. The platform is intended for personal and educational use.</p>
        <h2 className="text-2xl font-semibold text-slate-800 dark:text-white mt-8 mb-4">2. AI-Generated Content Disclaimer</h2>
        <p>The content generated by our AI tools (including resumes, presentations, and captions) is provided "as is". We are not responsible for inaccuracies. Always review and verify the content before use.</p>
        <h2 className="text-2xl font-semibold text-slate-800 dark:text-white mt-8 mb-4">3. Intellectual Property</h2>
        <p>You retain the rights to the content you generate. The StudentAI Tools intellectual property remains ours.</p>
        <h2 className="text-2xl font-semibold text-slate-800 dark:text-white mt-8 mb-4">4. Liability Limitations</h2>
        <p>StudentAI Tools and its creators shall not be liable for any direct, indirect, incidental, or consequential damages resulting from the use or inability to use the services.</p>
      </div>
    </div>
  </div>
);

export default Terms;
