import { useState, useRef } from 'react';
import SEO from '../../components/SEO';
import { FileImage, FileText, Download, Loader2, CheckCircle, HelpCircle, Shield, Zap, Layout, Plus, Trash2, GripVertical } from 'lucide-react';
import { jsPDF } from 'jspdf';

const ImageToPdf = () => {
    const [images, setImages] = useState([]); // [{id, file, previewUrl}]
    const [loading, setLoading] = useState(false);
    const [dragOverIndex, setDragOverIndex] = useState(null);
    const dragItem = useRef(null);
    const fileInputRef = useRef(null);

    const handleFileChange = (e) => {
        const files = Array.from(e.target.files);
        if (!files.length) return;
        const newImages = files.map((file) => ({
            id: `${file.name}-${Date.now()}-${Math.random()}`,
            file,
            previewUrl: URL.createObjectURL(file),
        }));
        setImages((prev) => [...prev, ...newImages]);
        // reset input so same file can be added again
        e.target.value = '';
    };

    const removeImage = (id) => {
        setImages((prev) => {
            const removed = prev.find((img) => img.id === id);
            if (removed) URL.revokeObjectURL(removed.previewUrl);
            return prev.filter((img) => img.id !== id);
        });
    };

    const clearAll = () => {
        images.forEach((img) => URL.revokeObjectURL(img.previewUrl));
        setImages([]);
    };

    /* ---- drag-to-reorder ---- */
    const handleDragStart = (index) => { dragItem.current = index; };
    const handleDragEnter = (index) => { setDragOverIndex(index); };
    const handleDragEnd = () => {
        if (dragItem.current === null || dragOverIndex === null || dragItem.current === dragOverIndex) {
            dragItem.current = null;
            setDragOverIndex(null);
            return;
        }
        const reordered = [...images];
        const [moved] = reordered.splice(dragItem.current, 1);
        reordered.splice(dragOverIndex, 0, moved);
        setImages(reordered);
        dragItem.current = null;
        setDragOverIndex(null);
    };

    const convertToPdf = async () => {
        if (!images.length) return;
        setLoading(true);
        try {
            let pdf = null;

            for (let i = 0; i < images.length; i++) {
                const { previewUrl } = images[i];
                const img = new Image();
                img.src = previewUrl;
                await new Promise((resolve) => { img.onload = resolve; });

                const orientation = img.width > img.height ? 'landscape' : 'portrait';

                if (i === 0) {
                    pdf = new jsPDF({ orientation, unit: 'px', format: [img.width, img.height] });
                } else {
                    pdf.addPage([img.width, img.height], orientation);
                }
                pdf.addImage(img, 'JPEG', 0, 0, img.width, img.height);
            }

            pdf.save(`studentai_pdf_${Date.now()}.pdf`);
        } catch (err) {
            console.error('PDF Conversion Error:', err);
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="min-h-screen pt-24 pb-12 bg-slate-50 dark:bg-slate-900">
            <SEO
                title="Free Image to PDF Converter — JPG, PNG & WebP, Multiple Pages (2026)"
                canonical="/tools/image-to-pdf"
                description="Convert multiple JPG, PNG, and WebP images into a single high-quality PDF instantly. 100% free, secure, browser-based. Drag to reorder pages. Perfect for student assignments."
                keywords="image to pdf, jpg to pdf, png to pdf, multiple images to pdf, student assignment tool, photo to pdf free"
                schema={[
                  {
                    "@context": "https://schema.org",
                    "@type": "SoftwareApplication",
                    "name": "Image to PDF Converter",
                    "operatingSystem": "Web",
                    "applicationCategory": "UtilitiesApplication",
                    "description": "Professional-grade local image-to-PDF converter with multi-image support, drag-to-reorder, and zero server upload.",
                    "offers": { "@type": "Offer", "price": "0", "priceCurrency": "INR" }
                  },
                  {
                    "@context": "https://schema.org",
                    "@type": "FAQPage",
                    "mainEntity": [
                      { "@type": "Question", "name": "Can I convert multiple images into a single PDF?", "acceptedAnswer": { "@type": "Answer", "text": "Yes. You can add as many JPG, PNG, or WebP images as you need. Each image becomes one page in the final PDF. Drag the thumbnails to reorder pages before downloading." } },
                      { "@type": "Question", "name": "Is the conversion done on my device or a server?", "acceptedAnswer": { "@type": "Answer", "text": "Entirely on your device. The PDF is generated by jsPDF running in your browser. Your images are never uploaded to any server, guaranteeing 100% privacy." } },
                      { "@type": "Question", "name": "Will the image quality be reduced in the PDF?", "acceptedAnswer": { "@type": "Answer", "text": "No. The original resolution of each image is preserved and embedded into the PDF at full quality. There is no compression applied." } },
                      { "@type": "Question", "name": "What image formats are supported?", "acceptedAnswer": { "@type": "Answer", "text": "Currently JPG, PNG, and WebP are supported. For other formats like BMP or TIFF, convert them to one of the supported formats first using a free image editor." } },
                      { "@type": "Question", "name": "Is there a page or file size limit?", "acceptedAnswer": { "@type": "Answer", "text": "There is no hard server limit since all processing is local. We recommend keeping each image under 10MB to avoid browser memory limitations on older devices." } }
                    ]
                  }
                ]}
            />

            <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
                <div className="text-center mb-12">
                    <div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-violet-50 dark:bg-violet-900/30 text-violet-600 mb-4 transition-transform hover:-translate-y-1 hover:scale-105 shadow-lg shadow-violet-500/20">
                        <FileText className="w-8 h-8" />
                    </div>
                    <h1 className="text-4xl md:text-6xl font-extrabold text-slate-900 dark:text-white mb-4 tracking-tight">
                        Image to <span className="text-gradient" style={{ backgroundImage: 'linear-gradient(to right, #8b5cf6, #6366f1)', WebkitBackgroundClip: 'text', color: 'transparent' }}>PDF Converter</span>
                    </h1>
                    <p className="text-lg text-slate-600 dark:text-slate-400 max-w-2xl mx-auto leading-relaxed">
                        Add multiple images and merge them into one professional PDF — all inside your browser, nothing uploaded.
                    </p>
                </div>

                <div className="glass-card rounded-[2.5rem] shadow-2xl border border-slate-200 dark:border-slate-800 overflow-hidden mb-16">
                    <div className="p-8 md:p-12 bg-white/30 dark:bg-slate-950/20 backdrop-blur-md">

                        {/* Drop zone / Add more */}
                        <div
                            onClick={() => fileInputRef.current?.click()}
                            className="max-w-2xl mx-auto border-4 border-dashed border-violet-200 dark:border-violet-900/50 bg-violet-50/50 dark:bg-violet-900/10 rounded-[2rem] p-10 hover:border-violet-500 dark:hover:border-violet-500 transition-all cursor-pointer group flex flex-col items-center justify-center shadow-inner hover:bg-violet-50 dark:hover:bg-violet-900/20 mb-8"
                        >
                            <input
                                ref={fileInputRef}
                                type="file"
                                accept="image/png, image/jpeg, image/webp"
                                onChange={handleFileChange}
                                multiple
                                className="hidden"
                                aria-label="Upload Images"
                            />
                            <div className="w-20 h-20 mb-4 rounded-full bg-white dark:bg-slate-800 shadow-xl flex items-center justify-center group-hover:scale-110 transition-transform duration-500">
                                {images.length === 0
                                    ? <FileImage className="w-9 h-9 text-violet-500" />
                                    : <Plus className="w-9 h-9 text-violet-500" />}
                            </div>
                            <h3 className="text-xl font-black dark:text-white mb-1 group-hover:text-violet-600 dark:group-hover:text-violet-400 transition-colors">
                                {images.length === 0 ? 'Select or Drop Images Here' : 'Add More Images'}
                            </h3>
                            <p className="text-slate-500 dark:text-slate-400 font-medium text-sm">Supports JPG, PNG, WEBP · Select multiple at once</p>
                        </div>

                        {/* Image grid with reorder */}
                        {images.length > 0 && (
                            <div className="animate-in fade-in duration-300">
                                <div className="flex items-center justify-between mb-4 px-1">
                                    <p className="text-sm font-bold text-slate-500 dark:text-slate-400 uppercase tracking-widest">
                                        {images.length} Image{images.length > 1 ? 's' : ''} · Drag to reorder
                                    </p>
                                    <button
                                        onClick={clearAll}
                                        className="text-xs font-bold text-red-500 hover:text-red-600 flex items-center gap-1 transition-colors"
                                    >
                                        <Trash2 className="w-3.5 h-3.5" /> Clear All
                                    </button>
                                </div>

                                <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-4 mb-8">
                                    {images.map((img, index) => (
                                        <div
                                            key={img.id}
                                            draggable
                                            onDragStart={() => handleDragStart(index)}
                                            onDragEnter={() => handleDragEnter(index)}
                                            onDragEnd={handleDragEnd}
                                            onDragOver={(e) => e.preventDefault()}
                                            className={`relative rounded-2xl overflow-hidden border-2 transition-all group cursor-grab active:cursor-grabbing shadow-md ${
                                                dragOverIndex === index
                                                    ? 'border-violet-500 scale-95 opacity-70'
                                                    : 'border-white dark:border-slate-700 hover:border-violet-400'
                                            }`}
                                        >
                                            <img
                                                src={img.previewUrl}
                                                alt={`Page ${index + 1}`}
                                                className="w-full h-32 object-cover"
                                            />
                                            {/* Page number badge */}
                                            <div className="absolute bottom-2 left-2 bg-black/60 text-white text-xs font-bold px-2 py-0.5 rounded-full">
                                                Page {index + 1}
                                            </div>
                                            {/* Drag handle */}
                                            <div className="absolute top-2 left-2 bg-black/40 text-white rounded-full p-1 opacity-0 group-hover:opacity-100 transition-opacity">
                                                <GripVertical className="w-3.5 h-3.5" />
                                            </div>
                                            {/* Remove button */}
                                            <button
                                                onClick={() => removeImage(img.id)}
                                                className="absolute top-2 right-2 bg-red-500 hover:bg-red-600 text-white rounded-full p-1 opacity-0 group-hover:opacity-100 transition-all"
                                                title="Remove"
                                            >
                                                <Trash2 className="w-3.5 h-3.5" />
                                            </button>
                                        </div>
                                    ))}
                                </div>

                                <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
                                    <button
                                        onClick={convertToPdf}
                                        disabled={loading}
                                        className="w-full sm:w-auto bg-violet-600 hover:bg-violet-500 text-white font-black py-4 px-10 rounded-2xl transition-all shadow-xl shadow-violet-600/20 flex items-center justify-center gap-3 active:scale-[0.98] group disabled:opacity-50"
                                    >
                                        {loading ? <Loader2 className="animate-spin w-6 h-6" /> : <Download className="w-6 h-6 group-hover:-translate-y-1 transition-transform" />}
                                        <span className="text-lg tracking-tight">
                                            {loading ? 'Generating PDF...' : `Download PDF (${images.length} page${images.length > 1 ? 's' : ''})`}
                                        </span>
                                    </button>
                                </div>
                            </div>
                        )}
                    </div>
                </div>

                {/* Ad Space */}
                <div className="w-full h-24 glass-card rounded-2xl flex items-center justify-center text-slate-400 text-sm mb-16 border border-dashed border-slate-300 dark:border-slate-700/50">
                    Ad Placement - Document Tools Hub
                </div>

                {/* ── E-E-A-T Content Section ─────────────────────────────────── */}
                <div className="max-w-4xl mx-auto space-y-14 mb-20">

                  {/* Introduction */}
                  <section className="bg-white dark:bg-slate-800/50 rounded-[3rem] p-10 md:p-14 border border-slate-200 dark:border-slate-700 shadow-sm">
                    <h2 className="text-3xl font-extrabold text-slate-900 dark:text-white mb-6">Why Students Need an Image to PDF Converter</h2>
                    <p className="text-slate-600 dark:text-slate-400 leading-relaxed mb-5">
                      Most universities and colleges require assignment submissions in PDF format. The problem? Students often have their work in the form of photos — handwritten lab reports, hand-drawn diagrams, whiteboard sketches, or images of physical artwork. Emailing or uploading a folder of JPGs is unprofessional and frequently rejected by submission portals.
                    </p>
                    <p className="text-slate-600 dark:text-slate-400 leading-relaxed mb-5">
                      An <strong>Image to PDF converter</strong> solves this instantly. In under 60 seconds, you can consolidate 10 separate image files into a single, professionally paginated PDF document that is ready for upload to Moodle, Turnitin, Google Classroom, or any submission system.
                    </p>
                    <p className="text-slate-600 dark:text-slate-400 leading-relaxed">
                      What makes our tool different from online alternatives like iLovePDF or SmallPDF is that <strong>your images never leave your device</strong>. The entire PDF is generated locally in your browser using the <em>jsPDF</em> library — no upload, no wait, no privacy risk.
                    </p>
                  </section>

                  {/* How It Works */}
                  <section>
                    <h2 className="text-3xl font-extrabold text-slate-900 dark:text-white mb-8">How the Image to PDF Converter Works</h2>
                    <div className="grid md:grid-cols-4 gap-5">
                      {[
                        { step: '01', title: 'Select Images', desc: 'Click the upload zone or drag your JPG, PNG, or WebP files. You can select multiple images at once from your Photos app, file manager, or desktop.' },
                        { step: '02', title: 'Reorder Pages', desc: 'Drag the image thumbnails into the exact order you want. Each thumbnail shows a "Page X" badge so you can track the sequence at a glance.' },
                        { step: '03', title: 'Generate PDF', desc: 'Click "Download PDF" and jsPDF creates the document in-browser, fitting each image to its own page with the correct orientation (portrait or landscape).' },
                        { step: '04', title: 'Download & Submit', desc: 'The PDF is saved directly to your Downloads folder. Open it to verify, then upload it to your submission portal — done.' },
                      ].map((item, i) => (
                        <div key={i} className="bg-white dark:bg-slate-800/50 rounded-3xl p-6 border border-slate-200 dark:border-slate-700 relative overflow-hidden">
                          <div className="text-5xl font-black text-slate-100 dark:text-slate-800 absolute -top-2 -right-2 select-none">{item.step}</div>
                          <div className="w-9 h-9 rounded-xl bg-violet-100 dark:bg-violet-900/40 text-violet-600 flex items-center justify-center font-bold text-xs mb-3 relative z-10">{item.step}</div>
                          <h3 className="text-base font-bold text-slate-900 dark:text-white mb-2 relative z-10">{item.title}</h3>
                          <p className="text-xs text-slate-600 dark:text-slate-400 leading-relaxed relative z-10">{item.desc}</p>
                        </div>
                      ))}
                    </div>
                  </section>

                  {/* Use Cases */}
                  <section className="bg-violet-50 dark:bg-violet-900/10 rounded-[3rem] p-10 md:p-14 border border-violet-100 dark:border-violet-800/30">
                    <h2 className="text-3xl font-extrabold text-slate-900 dark:text-white mb-8">5 Common Student Scenarios for Image-to-PDF</h2>
                    <div className="space-y-5">
                      {[
                        { n: '1', title: 'Submitting Handwritten Assignments', desc: 'Many professors still require handwritten work — especially for Maths, Chemistry, and language courses. After photographing each page of your work with your phone, use this tool to merge all photos into a single multi-page PDF for online submission.' },
                        { n: '2', title: 'Lab Report Diagrams & Sketches', desc: 'Lab reports often include hand-drawn circuit diagrams, biological specimens, or molecular structures. Converting these to PDF keeps them alongside your typed report in a single document, making grading easier for your professor.' },
                        { n: '3', title: 'Portfolio Submissions for Art & Design', desc: 'Creative students often photograph their physical artwork (paintings, sculptures, typography work) on their phone. This tool lets you sequence your portfolio images into a beautifully ordered PDF for course or scholarship submissions.' },
                        { n: '4', title: 'Digitising Printed Reference Materials', desc: 'Sometimes you get a physical handout with no digital version. Photograph each page and convert them to PDF to keep a searchable, shareable digital archive of your printed study materials.' },
                        { n: '5', title: 'Creating Visual Study Guides', desc: 'If you learn visually, photograph mind maps, whiteboard sessions, and post-it note summaries. Convert them to a PDF to create a compact, printable visual revision guide you can share with classmates.' },
                      ].map((uc, i) => (
                        <div key={i} className="flex gap-5 bg-white dark:bg-slate-800/50 rounded-2xl p-6 border border-violet-100 dark:border-violet-800/20">
                          <div className="w-10 h-10 rounded-xl bg-violet-600 text-white flex items-center justify-center font-bold flex-shrink-0 text-sm">{uc.n}</div>
                          <div>
                            <h3 className="font-bold text-slate-900 dark:text-white mb-1">{uc.title}</h3>
                            <p className="text-sm text-slate-600 dark:text-slate-400 leading-relaxed">{uc.desc}</p>
                          </div>
                        </div>
                      ))}
                    </div>
                  </section>

                  {/* Features + FAQ */}
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-10">
                    <div className="space-y-8">
                      <h2 className="text-2xl font-extrabold text-slate-900 dark:text-white">Why Use Our Converter?</h2>
                      {[
                        { title: '100% Privacy — Zero Upload', desc: 'Your images are never sent to a server. jsPDF generates the PDF entirely within your browser tab, so sensitive documents stay on your device.', icon: Shield },
                        { title: 'Drag-to-Reorder Pages', desc: 'Our converter uniquely lets you reorder images by dragging thumbnails before conversion — ensuring your document pages appear in the exact sequence you intend.', icon: Layout },
                        { title: 'Auto Orientation Detection', desc: 'Landscape photos create landscape pages. Portrait photos create portrait pages. Each image fits its page perfectly without cropping or distortion.', icon: Zap }
                      ].map((item, i) => (
                        <div key={i} className="flex gap-5">
                          <div className="w-12 h-12 rounded-2xl bg-violet-50 dark:bg-violet-900/30 text-violet-600 flex items-center justify-center flex-shrink-0">
                            <item.icon className="w-6 h-6" />
                          </div>
                          <div>
                            <h3 className="font-bold text-slate-900 dark:text-white mb-1">{item.title}</h3>
                            <p className="text-sm text-slate-600 dark:text-slate-400 leading-relaxed">{item.desc}</p>
                          </div>
                        </div>
                      ))}
                    </div>

                    <div className="glass-card rounded-[2rem] p-8 relative overflow-hidden h-fit">
                      <div className="absolute -top-20 -right-20 w-56 h-56 bg-violet-500/8 rounded-full blur-3xl"></div>
                      <h2 className="text-2xl font-extrabold dark:text-white mb-6 relative z-10">Frequently Asked Questions</h2>
                      <div className="space-y-5 relative z-10">
                        {[
                          { q: 'Can I add multiple images at once?', a: 'Yes. Click the upload zone and use Ctrl+Click (Windows) or Cmd+Click (Mac) to select multiple files simultaneously. They are all added to your page queue.' },
                          { q: 'Does it compress or reduce image quality?', a: 'No. Each image is embedded at its original resolution. The final PDF file size will be approximately the sum of all your image file sizes.' },
                          { q: 'What image formats are supported?', a: 'JPG, PNG, and WebP are all fully supported. For other formats (BMP, TIFF, HEIC), convert them first using a free image editor or your phone\'s Photos app.' },
                          { q: 'Is there a limit on how many images I can add?', a: 'No hard limit. However, adding a very large number of high-resolution images may slow down older devices due to browser memory limits. We recommend batches of 20-30 images maximum.' },
                          { q: 'Can I remove an image after adding it?', a: 'Yes. Each thumbnail has a red trash icon that appears on hover. Click it to remove that specific image from the queue without affecting the others.' },
                          { q: 'Does it work on mobile phones?', a: 'Yes. The converter is fully responsive and works on iOS Safari and Android Chrome. You can directly access your phone\'s camera roll to select photos.' },
                        ].map((faq, i) => (
                          <div key={i} className="pb-4 border-b border-slate-100 dark:border-slate-800 last:border-0">
                            <h3 className="font-bold text-slate-900 dark:text-white mb-1.5 flex items-center gap-2 text-sm">
                              <HelpCircle className="w-4 h-4 text-violet-500 flex-shrink-0" /> {faq.q}
                            </h3>
                            <p className="text-slate-500 dark:text-slate-400 text-sm leading-relaxed">{faq.a}</p>
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>
                </div>

            </div>
        </div>
    );
};

export default ImageToPdf;
